server:
  port: 8081
spring:
  application:
    name: openai-service
#    chatgpt
openai:
  token: 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
  timeout: 5000
#proxy:
#  host: 127.0.0.1
#  port: 10809